packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@ffprobe-installer/darwin-arm64': true
  '@ffprobe-installer/darwin-x64': true
  '@ffprobe-installer/linux-arm': true
  '@ffprobe-installer/linux-arm64': true
  '@ffprobe-installer/linux-ia32': true
  '@ffprobe-installer/linux-x64': true
  '@ffprobe-installer/win32-ia32': true
  '@ffprobe-installer/win32-x64': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  prisma: true
